name: GitHub Actions Demo
run-name: Bounce CI/CD
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: install client dependencies
              working-directory: ./client
              run: npm ci

            - name: install server dependencies
              working-directory: ./server
              run: npm ci

            - name: Install playwright browsers
              working-directory: ./client
              run: npx playwright install --with-deps

            - name: "Run e2e tests"
              working-directory: ./client
              run: npx playwright test
              env:
                  PORT: 5000
                  CLIENT_HOST: http://localhost:5173

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: client/playwright-report/
                  retention-days: 30
