name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [24.x]
        steps:
            - uses: actions/checkout@v4
            - name: Starting node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
            - name: install modules
              run: npm install
            - name: build client app
              working-directory: ./client
              run: npm run build
            - name: build server app
              working-directory: ./server
              run: npm run build
            - name: run unit tests
              working-directory: ./client
              run: npm run test
